### PR TITLE
Re-cut

### PR DESCRIPTION
**Pull request by Sparks29032**

### CODE REVIEW

**Comment by bobleesj** [comment]
@sbillinge Once 0.5.0 `bg-mpl-stylesheets` is available on conda-forge, the test will pass. I have tested this package locally using the 0.5.0rc0` available on pip.

**Comment by Sparks29032** [comment]
Thanks, seems good then.

**Comment by sbillinge** [comment]
OK, 0.5.0 is on pypi, so we should be able to test this in a couple of hours if we lucky, or else tomorrow.

**Comment by bobleesj** [comment]
@sbillinge  bg-mpl-stylesheets 0.5.0 feedstock PR requested https://github.com/conda-forge/bg-mpl-stylesheets-feedstock/pull/28

will take about ~15-20 mins for the package to appear via conda-forge channel. So let's re-run the CI then!

**Comment by bobleesj** [comment]
@sbillinge 0.5.0 `bg-mpl-stylesheets` now available on conda-forge. https://anaconda.org/conda-forge/bg-mpl-stylesheets/files

can we re-run the CI?

**Comment by bobleesj** [comment]
Great

**Comment by sbillinge** [comment]
@Sparks29032 @bobleesj sweet, we are running in 3.13!

**Pull request merged**
