### PR TITLE
GH action to build and deploy docs

### LINKED ISSUE #52: make GH action that publishes documentation automatically on release

### PR DESCRIPTION
**Pull request by cadenmyers13**
Closes #52 

I mostly used the code from `docs.yml` in `diffpy.utils`. I removed one portion because it was failing. I'm unsure if that line was needed.

### CODE REVIEW

**Review by sbillinge — COMMENTED** [review]
please see inline comment.  That section you deleted is needed so you will have to debug.

Please try and keep your commit messages informational with what edit is in each commit.

**Comment by sbillinge** [comment]
@cadenmyers13 please also see how I edited the title and first comment of the PR and try and do it similarly.

**Comment by sbillinge** [comment]
I think you will have to revert the last commit to get the build section back and I or @Sparks29032 can merge and see what happens when it tries to run.  This Action won't run until it is merged.

**Comment by Sparks29032** [comment]
We can try testing it by adding `pull_request:` to the `on:` section. This way we can test the build prior to merge. If the documentation builds properly, we would need to remove the `pull_request:` trigger then merge.

**Comment by sbillinge** [comment]
> We can try testing it by adding `pull_request:` to the `on:` section. This way we can test the build prior to merge. If the documentation builds properly, we would need to remove the `pull_request:` trigger then merge.

yes, that's a great idea. @cadenmyers13 please can you revert the last commit to get the section back and add along with `push:` and `release:` please add `pull_request` and then push again?

**Comment by cadenmyers13** [comment]
Sounds good! I’ll work on it. On May 16, 2024, at 9:15 PM, Simon Billinge ***@***.***> wrote:﻿

We can try testing it by adding pull_request: to the on: section. This way we can test the build prior to merge. If the documentation builds properly, we would need to remove the pull_request: trigger then merge.

yes, that's a great idea. @cadenmyers13 please can you revert the last commit to get the section back and add along with push: and release: please add pull_request and then push again?

**Comment by Sparks29032** [comment]
Errors in documentation build fixed in PR #91. Given the difference in directory structure between `diffpy.utils` and `diffpy.pdfmorph`, the `build documents` action for `diffpy.pdfmorph` should look like the following (slight difference from that in `diffpy.utils`).

```
- name: build documents
        run: make -C doc html
```

**Comment by sbillinge** [comment]
Thanks @Sparks29032 .  As I noted in your #91 PR, rather than changing the path in the workflow, I would rather change the directory structure to be uniform across projects.  This is way less headaches and bugfixing in the long run.

 I think `diffpy.utils` is more uniform with the other diffpy packages than pdfmorph, so I think it is better that we change the directory structure here to be like there (and leave the workflow yml file unmodified).  @cadenmyers13 please could you make that change.

As a favor, while we are at it, @cadenmyers13 please could you put a PR into diffpy.labpdfproc (Yucong's project) with the same change in directory structure, to make that compliant?  I think that project also has an issue open to make a doc building workflow, so perhaps you could also close that one at the same time?  Please let Yucong know you are working on that though so we don't duplicate effort.

**Comment by cadenmyers13** [comment]
> Thanks @Sparks29032 . As I noted in your #91 PR, rather than changing the path in the workflow, I would rather change the directory structure to be uniform across projects. This is way less headaches and bugfixing in the long run.
> 
> I think `diffpy.utils` is more uniform with the other diffpy packages than pdfmorph, so I think it is better that we change the directory structure here to be like there (and leave the workflow yml file unmodified). @cadenmyers13 please could you make that change.
> 
> As a favor, while we are at it, @cadenmyers13 please could you put a PR into diffpy.labpdfproc (Yucong's project) with the same change in directory structure, to make that compliant? I think that project also has an issue open to make a doc building workflow, so perhaps you could also close that one at the same time? Please let Yucong know you are working on that though so we don't duplicate effort.

**Comment by cadenmyers13** [comment]
@sbillinge Getting started on all of this. I'll let Yucong know.

**Comment by Sparks29032** [comment]
@cadenmyers13 When you change the path structure, make sure all referenced files in the `.rst`s are changed as well. For instance,  `../..` -> `../../..`, `../../CHANGELOG.rst` -> `../../../CHANGELOG.rst`, and `../../src` -> `../../../src`.

**Comment by sbillinge** [comment]
@cadenmyers13 this is good!  Is there a reason you didn't do this on a clean branch from a fully sync'ed main?  There is a big PR merged from Andrew and we want to build this on that.  Rather than merge that, I suggest that you close this and do it over.

**Comment by cadenmyers13** [comment]
@Sparks29032 I think it automatically updated all the file pathways. 

@sbillinge No reason. I guess I'm still learning the utility of git and GitHub in that regard lol... Let me try to figure it out and I'll reach out if I have questions!

**Comment by sbillinge** [comment]
> @Sparks29032 I think it automatically updated all the file pathways.
> 
> @sbillinge No reason. I guess I'm still learning the utility of git and GitHub in that regard lol... Let me try to figure it out and I'll reach out if I have questions!

no problem @cadenmyers13 , it is a steep learning curve.   We usually do it the way you did it so you are all good, but in this case the discussion mentioned that we would need a clean branch.  There are somewhat advanced ways of merging commits across branches for more advanced behavior, but I prefer to have you just learn really how git works by doing simple things at the beginning.  Make sure you understand the difference between what you did and doing the same thing on a clean branch.  If you are not sure, ask.

Regarding your other comment, I think he means updating this in the rst files themselves.  If you used the "refactor" function in PyCharm they may have been updated, but I just want to make sure.  We don't have an automated test for this, but build the documentation locally and then go through it and make sure all the links work and the pages cross-refence correctly by clicking on all the links.....  It sounds alot but should be quick.

**Comment by cadenmyers13** [comment]
@sbillinge I'm not seeing where the conflicting files reside. On my local these three files are stored under `..doc/manual/source/<file>`. If I try to add and commit these changes it says there's nothing to commit. Where are the conflicting files located? Does this conflict arise from the [original repository](https://github.com/diffpy/diffpy.pdfmorph)?

**Comment by sbillinge** [comment]
There will be no conflicts to clear of you are on a new clean branch

**Comment by sbillinge** [comment]
I can zoom in 15 mins and we can discuss

**Comment by cadenmyers13** [comment]
okay sounds good

**Comment by sbillinge** [comment]
It's important to understand the basic git stuff and it will all be clear

**Pull request closed without merging**
