### PR TITLE
Ensure evaluation

### PR DESCRIPTION
**Pull request by Sparks29032**
Need `${{}}` otherwise the inner conditional will not be evaluated (without evaluation, the `if` statement evaluates the string literal which will always return true).

Also update `peaceiris` version and include `release` as a trigger for deploying documentation.

### CODE REVIEW

**Comment by sbillinge** [comment]
thanks @Sparks29032

**Comment by sbillinge** [comment]
@cadenmyers13 can we put these same things into diffpy.utils and also diffpy.labpdfproc?  In principle we would like to add them to all the diffpy projects!   Another project is to create a cookiecutter for group releases and that could have these in them so all future repos look this way by default.

**Comment by cadenmyers13** [comment]
> @cadenmyers13 can we put these same things into diffpy.utils and also diffpy.labpdfproc? In principle we would like to add them to all the diffpy projects! Another project is to create a cookiecutter for group releases and that could have these in them so all future repos look this way by default.

Yep. ill take care of it!

**Comment by cadenmyers13** [comment]
> > @cadenmyers13 can we put these same things into diffpy.utils and also diffpy.labpdfproc? In principle we would like to add them to all the diffpy projects! Another project is to create a cookiecutter for group releases and that could have these in them so all future repos look this way by default.
> 
> Yep. ill take care of it!

Looks like Andrew took care of it for diffpy.utils, ill put it in diffpy.labpdfproc

**Pull request merged**
